local WheelSlots =
{
    SLOT_GREEN_200 = 1,
    SLOT_GREEN_TOP_150 = 2,
    SLOT_GREEN_TOP_100 = 3,

    SLOT_RED_TOP_100 = 4,
    SLOT_RED_TOP_150 = 5,
    SLOT_RED_200 = 6,

    SLOT_GREEN_BOTTOM_150 = 7,
    SLOT_GREEN_MIDDLE_100 = 8,
    SLOT_GREEN_TOP_75 = 9,

    SLOT_RED_TOP_75 = 10,
    SLOT_RED_MIDDLE_100 = 11,
    SLOT_RED_BOTTOM_150 = 12,

    SLOT_GREEN_BOTTOM_100 = 13,
    SLOT_GREEN_BOTTOM_75 = 14,
    SLOT_GREEN_50 = 15,

    SLOT_RED_50 = 16,
    SLOT_RED_BOTTOM_75 = 17,
    SLOT_RED_BOTTOM_100 = 18,

    SLOT_BLUE_TOP_100 = 19,
    SLOT_BLUE_TOP_75 = 20,
    SLOT_BLUE_50 = 21,

    SLOT_PURPLE_50 = 22,
    SLOT_PURPLE_TOP_75 = 23,
    SLOT_PURPLE_TOP_100 = 24,

    SLOT_BLUE_TOP_150 = 25,
    SLOT_BLUE_MIDDLE_100 = 26,
    SLOT_BLUE_BOTTOM_75 = 27,

    SLOT_PURPLE_BOTTOM_75 = 28,
    SLOT_PURPLE_MIDDLE_100 = 29,
    SLOT_PURPLE_TOP_150 = 30,

    SLOT_BLUE_200 = 31,
    SLOT_BLUE_BOTTOM_150 = 32,
    SLOT_BLUE_BOTTOM_100 = 33,

    SLOT_PURPLE_BOTTOM_100 = 34,
    SLOT_PURPLE_BOTTOM_150 = 35,
    SLOT_PURPLE_200 = 36,
}

local WheelSlotsParser = {
    [WheelSlots.SLOT_GREEN_200] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 9,
        currentPoints = 0,
        totalPoints = 200,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = {},
        left = 80,
        top = 80,
    },
    [WheelSlots.SLOT_GREEN_TOP_150] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 8,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_GREEN_200, WheelSlots.SLOT_GREEN_BOTTOM_150 },
        top = 90,
        left = 160,
    },
    [WheelSlots.SLOT_GREEN_BOTTOM_150] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 7,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_GREEN_200, WheelSlots.SLOT_GREEN_TOP_150 },
        top = 160,
        left = 90
    },
    [WheelSlots.SLOT_GREEN_TOP_100] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 6,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_GREEN_TOP_150, WheelSlots.SLOT_RED_TOP_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 120,
        left = 210
    },
    [WheelSlots.SLOT_GREEN_MIDDLE_100] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 5,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_GREEN_BOTTOM_150, WheelSlots.SLOT_GREEN_TOP_150, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 155,
        left = 155,
    },
    [WheelSlots.SLOT_GREEN_BOTTOM_100] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 4,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_GREEN_BOTTOM_150, WheelSlots.SLOT_BLUE_TOP_100, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 215,
        left = 120
    },
    [WheelSlots.SLOT_GREEN_TOP_75] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 3,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_GREEN_MIDDLE_100, WheelSlots.SLOT_GREEN_TOP_100, WheelSlots.SLOT_RED_TOP_75, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 175,
        left = 215
    },
    [WheelSlots.SLOT_GREEN_BOTTOM_75] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 2,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_GREEN_MIDDLE_100, WheelSlots.SLOT_GREEN_BOTTOM_100, WheelSlots.SLOT_BLUE_TOP_75, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 220,
        left = 175
    },
    [WheelSlots.SLOT_GREEN_50] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 1,
        currentPoints = 0,
        totalPoints = 50,
        adjacents = { WheelSlots.SLOT_GREEN_BOTTOM_75, WheelSlots.SLOT_GREEN_TOP_75, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 225,
        left = 225
    },
    [WheelSlots.SLOT_RED_200] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 9,
        currentPoints = 0,
        totalPoints = 200,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = {},
        top = 80,
        left = 410,
    },
    [WheelSlots.SLOT_RED_TOP_150] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 8,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_RED_200, WheelSlots.SLOT_RED_BOTTOM_150 },
        top = 85,
        left = 335
    },
    [WheelSlots.SLOT_RED_BOTTOM_150] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 7,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_RED_200, WheelSlots.SLOT_RED_TOP_150 },
        top = 155,
        left = 405
    },
    [WheelSlots.SLOT_RED_TOP_100] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 6,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_RED_TOP_150, WheelSlots.SLOT_GREEN_TOP_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 120,
        left = 280
    },
    [WheelSlots.SLOT_RED_MIDDLE_100] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 5,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_RED_TOP_150, WheelSlots.SLOT_RED_BOTTOM_150 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 155,
        left = 340,
    },
    [WheelSlots.SLOT_RED_BOTTOM_100] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 4,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_RED_BOTTOM_150, WheelSlots.SLOT_PURPLE_BOTTOM_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 215,
        left = 370
    },
    [WheelSlots.SLOT_RED_TOP_75] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 3,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_RED_TOP_100, WheelSlots.SLOT_RED_MIDDLE_100, WheelSlots.SLOT_GREEN_TOP_75, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 175,
        left = 275
    },
    [WheelSlots.SLOT_RED_BOTTOM_75] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 2,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_RED_BOTTOM_100, WheelSlots.SLOT_RED_MIDDLE_100, WheelSlots.SLOT_PURPLE_BOTTOM_75, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 215,
        left = 315
    },
    [WheelSlots.SLOT_RED_50] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 1,
        currentPoints = 0,
        totalPoints = 50,
        adjacents = { WheelSlots.SLOT_RED_BOTTOM_75, WheelSlots.SLOT_RED_TOP_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 225,
        left = 266
    },
    [WheelSlots.SLOT_BLUE_200] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 9,
        currentPoints = 0,
        totalPoints = 200,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = {},
        top = 412,
        left = 80
    },
    [WheelSlots.SLOT_BLUE_TOP_150] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 7,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_BLUE_200, WheelSlots.SLOT_BLUE_BOTTOM_150, WheelSlots.SLOT_BLUE_MIDDLE_100, WheelSlots.SLOT_BLUE_TOP_100 },
        top = 335,
        left = 90
    },
    [WheelSlots.SLOT_BLUE_BOTTOM_150] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 8,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_BLUE_200, WheelSlots.SLOT_BLUE_TOP_150, WheelSlots.SLOT_BLUE_MIDDLE_100, WheelSlots.SLOT_BLUE_BOTTOM_100 },
        top = 405,
        left = 155
    },
    [WheelSlots.SLOT_BLUE_TOP_100] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 4,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_BLUE_BOTTOM_150, WheelSlots.SLOT_PURPLE_TOP_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 280,
        left = 120,
    },
    [WheelSlots.SLOT_BLUE_MIDDLE_100] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 5,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_BLUE_BOTTOM_150, WheelSlots.SLOT_BLUE_TOP_150 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 335,
        left = 155,
    },
    [WheelSlots.SLOT_BLUE_BOTTOM_100] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 6,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_BLUE_TOP_150, WheelSlots.SLOT_PURPLE_BOTTOM_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 370,
        left = 215
    },
    [WheelSlots.SLOT_BLUE_TOP_75] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 2,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_BLUE_MIDDLE_100, WheelSlots.SLOT_BLUE_TOP_100, WheelSlots.SLOT_PURPLE_TOP_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 275,
        left = 175,
    },
    [WheelSlots.SLOT_BLUE_BOTTOM_75] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 3,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_BLUE_MIDDLE_100, WheelSlots.SLOT_BLUE_BOTTOM_100, WheelSlots.SLOT_PURPLE_BOTTOM_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 315,
        left = 215
    },
    [WheelSlots.SLOT_BLUE_50] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 1,
        currentPoints = 0,
        totalPoints = 50,
        adjacents = { WheelSlots.SLOT_BLUE_BOTTOM_75, WheelSlots.SLOT_BLUE_TOP_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 265,
        left = 225
    },
    [WheelSlots.SLOT_PURPLE_200] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 9,
        currentPoints = 0,
        totalPoints = 200,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = {},
        top = 412,
        left = 412,
    },
    [WheelSlots.SLOT_PURPLE_TOP_150] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 7,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_PURPLE_200, WheelSlots.SLOT_PURPLE_BOTTOM_150 },
        top = 335,
        left = 405,
    },
    [WheelSlots.SLOT_PURPLE_BOTTOM_150] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 8,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_PURPLE_200, WheelSlots.SLOT_PURPLE_TOP_150 },
        top = 405,
        left = 335
    },
    [WheelSlots.SLOT_PURPLE_TOP_100] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 4,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_PURPLE_TOP_150, WheelSlots.SLOT_RED_BOTTOM_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 280,
        left = 370,
    },
    [WheelSlots.SLOT_PURPLE_MIDDLE_100] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 5,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_PURPLE_TOP_150, WheelSlots.SLOT_PURPLE_BOTTOM_150 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 340,
        left = 335,
    },
    [WheelSlots.SLOT_PURPLE_BOTTOM_100] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 6,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_PURPLE_BOTTOM_150, WheelSlots.SLOT_RED_BOTTOM_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 370,
        left = 280
    },
    [WheelSlots.SLOT_PURPLE_TOP_75] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 2,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_PURPLE_MIDDLE_100, WheelSlots.SLOT_PURPLE_TOP_100, WheelSlots.SLOT_RED_BOTTOM_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 275,
        left = 315
    },
    [WheelSlots.SLOT_PURPLE_BOTTOM_75] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 3,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_PURPLE_MIDDLE_100, WheelSlots.SLOT_PURPLE_BOTTOM_100, WheelSlots.SLOT_RED_BOTTOM_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 315,
        left = 275
    },
    [WheelSlots.SLOT_PURPLE_50] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 1,
        currentPoints = 0,
        totalPoints = 50,
        adjacents = { WheelSlots.SLOT_PURPLE_BOTTOM_75, WheelSlots.SLOT_PURPLE_TOP_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        height = "522",
        width = "522",
        adjacentPath = "",
        borderPath = "",
        top = 265,
        left = 266
    },
}


local VocationConfig = {
    -- Basic vocation IDs
    KNIGHT = 1,
    PALADIN = 2,
    SORCERER = 3,
    DRUID = 4,
    MONK = 5,

    -- Minimum requirements
    MIN_LEVEL = 51,
    MIN_PROMOTED_VOCATION = 11,

    -- Mapping from promoted to basic vocations
    promotedToBasic = {
        [11] = 1, -- Elite Knight -> Knight
        [12] = 2, -- Royal Paladin -> Paladin
        [13] = 3, -- Master Sorcerer -> Sorcerer
        [14] = 4, -- Elder Druid -> Druid
        [15] = 5  -- Exalted Monk -> Monk
    },

    -- Images by vocation
    images = {
        [1] = '/images/game/wheel/wheel-vocations/backdrop_skillwheel_knight',
        [2] = '/images/game/wheel/wheel-vocations/backdrop_skillwheel_paladin',
        [3] = '/images/game/wheel/wheel-vocations/backdrop_skillwheel_sorcerer',
        [4] = '/images/game/wheel/wheel-vocations/backdrop_skillwheel_druid',
        [5] = '/images/game/wheel/wheel-vocations/backdrop_skillwheel_monk'
    },
}

local function getVocationImage(basicVocationId)
    if basicVocationId == VocationConfig.MONK and g_game.getClientVersion() < 1500 then
        return nil
    end
    return VocationConfig.images[basicVocationId]
end

local function getBasicVocation(vocationId)
    return VocationConfig.promotedToBasic[vocationId] or vocationId
end

local function handleLargePerkClip(vocationId, controller)
    if vocationId == VocationConfig.KNIGHT then
        controller.wheel.tlLargePerkClip = { x = 0, y = 0, width = 34, height = 34 }
        controller.wheel.trLargePerkClip = { x = 34, y = 0, width = 34, height = 34 }
        controller.wheel.blLargePerkClip = { x = 68, y = 0, width = 34, height = 34 }
        controller.wheel.brLargePerkClip = { x = 102, y = 0, width = 34, height = 34 }
    elseif vocationId == VocationConfig.PALADIN then
        controller.wheel.tlLargePerkClip = { x = 0, y = 0, width = 34, height = 34 }
        controller.wheel.trLargePerkClip = { x = 136, y = 0, width = 34, height = 34 }
        controller.wheel.blLargePerkClip = { x = 170, y = 0, width = 34, height = 34 }
        controller.wheel.brLargePerkClip = { x = 204, y = 0, width = 34, height = 34 }
    elseif vocationId == VocationConfig.SORCERER then
        controller.wheel.tlLargePerkClip = { x = 0, y = 0, width = 34, height = 34 }
        controller.wheel.trLargePerkClip = { x = 238, y = 0, width = 34, height = 34 }
        controller.wheel.blLargePerkClip = { x = 272, y = 0, width = 34, height = 34 }
        controller.wheel.brLargePerkClip = { x = 306, y = 0, width = 34, height = 34 }
    elseif vocationId == VocationConfig.DRUID then
        controller.wheel.tlLargePerkClip = { x = 0, y = 0, width = 34, height = 34 }
        controller.wheel.trLargePerkClip = { x = 374, y = 0, width = 34, height = 34 }
        controller.wheel.blLargePerkClip = { x = 340, y = 0, width = 34, height = 34 }
        controller.wheel.brLargePerkClip = { x = 408, y = 0, width = 34, height = 34 }
    elseif vocationId == VocationConfig.MONK then
        controller.wheel.tlLargePerkClip = { x = 0, y = 0, width = 34, height = 34 }
        controller.wheel.trLargePerkClip = { x = 442, y = 0, width = 34, height = 34 }
        controller.wheel.blLargePerkClip = { x = 476, y = 0, width = 34, height = 34 }
        controller.wheel.brLargePerkClip = { x = 510, y = 0, width = 34, height = 34 }
    end
end


local baseSlotIndex = {
    15, 16, 21, 22
}

local function isFirstSlot(index)
    return table.contains(baseSlotIndex, index)
end

local selectionBonus = {
    data = {},
    showButtons = false,
    canAdd = false,
    canRemove = false,
    showMoreDetails = false,
    moreDetailsTooltip = nil,
    moreDetails = nil,
    moreDetailsColor = "#c0c0c0",
    moreDetailsTitle = nil,
}

local informationButtonClips = {
    firstButton = {
        selected = "/images/game/wheel/informationSelection.png",
        unselected = "/images/game/wheel/small_information_button.png",
        unselectedClip = { x = 0, y = 0, width = 34, height = 34 },
        selectedClip = { x = 0, y = 0, width = 173, height = 34 },
        selectedWidth = 173,
        unselectedWidth = 34,
    },
    secondButton = {
        selected = "/images/game/wheel/manageSelect.png",
        unselected = "/images/game/wheel/small_manage_button.png",
        unselectedClip = { x = 0, y = 0, width = 34, height = 34 },
        selectedClip = { x = 0, y = 0, width = 173, height = 34 },
        disabledClip = { x = 0, y = 68, width = 34, height = 34 },
        selectedWidth = 173,
        unselectedWidth = 34,
    }
}

local baseWheelValues = {
    currentWindow = "main-window",
    showSummary = false,
    summary = {},
    clip = { x = 0, y = 34, width = 322, height = 34 },
    backdropVocationOverlay = nil,
    currentSelectSlotId = -1,
    selectedPerkDomain = -1,
    currentHoverSlotId = -1,
    currentPoints = 0,
    extraPoints = 0,
    totalPoints = 0,
    currentSelectSlotData = nil,
    data = {},
    passiveBorders = {
        TL = "/images/game/wheel/backdrop_skillwheel_largebonus_front0_TL.png",
        TR = "/images/game/wheel/backdrop_skillwheel_largebonus_front0_TR.png",
        BL = "/images/game/wheel/backdrop_skillwheel_largebonus_front0_BL.png",
        BR = "/images/game/wheel/backdrop_skillwheel_largebonus_front0_BR.png"
    },
    dedicationPerk = {
        hitPoints = 0,
        mana = 0,
        cap = 0,
        mitigation = "0%"
    },
    convictionPerks = {},
    vessels = {},
    revelationPerks = {
        damage = {
            name = "Damage and Healing",
            text = "0",
            tooltip = "",
        },
        avatar = {
            name = "Avatar Of Nature",
            text = "Locked",
            tooltip = "",
            message = ""
        },
        spellTR = {
            name = "Blessing of the Gr...",
            text = "Locked",
            tooltip = "Blessing of the Grave",
            message = "",
        },
        spellBL = {
            name = "Blessing of the Gr...",
            text = "Locked",
            tooltip = "Blessing of the Grave",
            message = "",
        },
        giftOfLife = {
            name = "Gift of Life",
            text = "Locked",
            tooltip = "Blessing of the Grave",
            message = "",
        }
    },
    extraPassivePoints = {},
    equipedGemBonuses = {},
    vesselEnabled = {},
    activeGems = {},
    selectionBonus = selectionBonus,
    slotProgressLabel = "0/50",
    slotProgressCurrent = 0,
    slotProgressTotal = 0,
    slotProgressWidth = 205,
    information = {
        hoveredSlotData = nil,
        data = {},
        slotProgressCurrent = 0,
        slotProgressTotal = 0,
        slotProgressLabel = "0/50",
        slotProgressWidth = 205,
        firstButton = {
            active = true,
            path = informationButtonClips.firstButton.selected,
            clip = informationButtonClips.firstButton.selectedClip,
            width = informationButtonClips.firstButton.selectedWidth
        },
        secondButton = {
            active = false,
            path = informationButtonClips.secondButton.unselected,
            clip = informationButtonClips.secondButton.unselectedClip,
            width = informationButtonClips.secondButton.unselectedWidth,
            disabled = true,
        }
    },
    gold = "0",
    lesserFragment = 0,
    greaterFragment = 0,
    cooldownTooltip =
    "Note: The cooldown of a spell cannot be reduced to less than 50%\nof its base cooldown by any means."
}


local function translateVocation(id)
    if id == 1 or id == 11 then
        return 8 -- ek
    elseif id == 2 or id == 12 then
        return 7 -- rp
    elseif id == 3 or id == 13 then
        return 5 -- ms
    elseif id == 4 or id == 14 then
        return 6 -- ed
    elseif id == 5 or id == 15 then
        return 9 -- em
    end
    return 0
end

local wheel = {
    WheelSlots = WheelSlots,
    WheelSlotsParser = WheelSlotsParser,
    getBasicVocation = getBasicVocation,
    getVocationImage = getVocationImage,
    handleLargePerkClip = handleLargePerkClip,
    isFirstSlot = isFirstSlot,
    baseWheelValues = baseWheelValues,
    baseSlotIndex = baseSlotIndex,
    translateVocation = translateVocation,
    selectionBonus = selectionBonus,
    informationButtonClips = informationButtonClips,
}

return wheel
