local WheelSlots =
{
    SLOT_GREEN_200 = 1,
    SLOT_GREEN_TOP_150 = 2,
    SLOT_GREEN_TOP_100 = 3,

    SLOT_RED_TOP_100 = 4,
    SLOT_RED_TOP_150 = 5,
    SLOT_RED_200 = 6,

    SLOT_GREEN_BOTTOM_150 = 7,
    SLOT_GREEN_MIDDLE_100 = 8,
    SLOT_GREEN_TOP_75 = 9,

    SLOT_RED_TOP_75 = 10,
    SLOT_RED_MIDDLE_100 = 11,
    SLOT_RED_BOTTOM_150 = 12,

    SLOT_GREEN_BOTTOM_100 = 13,
    SLOT_GREEN_BOTTOM_75 = 14,
    SLOT_GREEN_50 = 15,

    SLOT_RED_50 = 16,
    SLOT_RED_BOTTOM_75 = 17,
    SLOT_RED_BOTTOM_100 = 18,

    SLOT_BLUE_TOP_100 = 19,
    SLOT_BLUE_TOP_75 = 20,
    SLOT_BLUE_50 = 21,

    SLOT_PURPLE_50 = 22,
    SLOT_PURPLE_TOP_75 = 23,
    SLOT_PURPLE_TOP_100 = 24,

    SLOT_BLUE_TOP_150 = 25,
    SLOT_BLUE_MIDDLE_100 = 26,
    SLOT_BLUE_BOTTOM_75 = 27,

    SLOT_PURPLE_BOTTOM_75 = 28,
    SLOT_PURPLE_MIDDLE_100 = 29,
    SLOT_PURPLE_TOP_150 = 30,

    SLOT_BLUE_200 = 31,
    SLOT_BLUE_BOTTOM_150 = 32,
    SLOT_BLUE_BOTTOM_100 = 33,

    SLOT_PURPLE_BOTTOM_100 = 34,
    SLOT_PURPLE_BOTTOM_150 = 35,
    SLOT_PURPLE_200 = 36,
}

local WheelSlotsParser = {
    [WheelSlots.SLOT_GREEN_200] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 9,
        currentPoints = 0,
        totalPoints = 200,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = {}
    },
    [WheelSlots.SLOT_GREEN_TOP_150] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 8,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_GREEN_200, WheelSlots.SLOT_GREEN_BOTTOM_150 },
    },
    [WheelSlots.SLOT_GREEN_BOTTOM_150] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 7,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_GREEN_200, WheelSlots.SLOT_GREEN_TOP_150 },
    },
    [WheelSlots.SLOT_GREEN_TOP_100] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 6,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_GREEN_BOTTOM_150, WheelSlots.SLOT_RED_TOP_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_GREEN_MIDDLE_100] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 5,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_GREEN_BOTTOM_150, WheelSlots.SLOT_GREEN_TOP_150, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_GREEN_BOTTOM_100] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 4,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_GREEN_BOTTOM_150, WheelSlots.SLOT_BLUE_BOTTOM_100, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_GREEN_TOP_75] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 3,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_GREEN_MIDDLE_100, WheelSlots.SLOT_GREEN_TOP_100, WheelSlots.SLOT_RED_TOP_75, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_GREEN_BOTTOM_75] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 2,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_GREEN_MIDDLE_100, WheelSlots.SLOT_GREEN_BOTTOM_100, WheelSlots.SLOT_BLUE_BOTTOM_75, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_GREEN_50] = {
        quadrant = "top_left",
        border = "top_left",
        color = "TopLeft",
        index = 1,
        currentPoints = 0,
        totalPoints = 50,
        adjacents = { WheelSlots.SLOT_GREEN_BOTTOM_75, WheelSlots.SLOT_GREEN_TOP_75, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_RED_200] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 9,
        currentPoints = 0,
        totalPoints = 200,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = {},
    },
    [WheelSlots.SLOT_RED_TOP_150] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 8,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_RED_200, WheelSlots.SLOT_RED_BOTTOM_150 },
    },
    [WheelSlots.SLOT_RED_BOTTOM_150] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 7,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_RED_200, WheelSlots.SLOT_RED_TOP_150 },
    },
    [WheelSlots.SLOT_RED_TOP_100] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 6,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_RED_TOP_150, WheelSlots.SLOT_GREEN_TOP_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_RED_MIDDLE_100] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 5,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_RED_TOP_150, WheelSlots.SLOT_RED_BOTTOM_150 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_RED_BOTTOM_100] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 4,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_RED_BOTTOM_150, WheelSlots.SLOT_PURPLE_BOTTOM_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_RED_TOP_75] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 3,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_RED_TOP_100, WheelSlots.SLOT_RED_MIDDLE_100, WheelSlots.SLOT_GREEN_TOP_75, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_RED_BOTTOM_75] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 2,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_RED_BOTTOM_100, WheelSlots.SLOT_RED_MIDDLE_100, WheelSlots.SLOT_PURPLE_BOTTOM_75, },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_RED_50] = {
        quadrant = "top_right",
        border = "top_right",
        color = "TopRight",
        index = 1,
        currentPoints = 0,
        totalPoints = 50,
        adjacents = { WheelSlots.SLOT_RED_BOTTOM_75, WheelSlots.SLOT_RED_TOP_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_BLUE_200] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 9,
        currentPoints = 0,
        totalPoints = 200,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = {}
    },
    [WheelSlots.SLOT_BLUE_TOP_150] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 8,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_BLUE_200, WheelSlots.SLOT_BLUE_BOTTOM_150 },
    },
    [WheelSlots.SLOT_BLUE_BOTTOM_150] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 7,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_BLUE_200, WheelSlots.SLOT_BLUE_TOP_150 },
    },
    [WheelSlots.SLOT_BLUE_TOP_100] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 4,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_BLUE_BOTTOM_150, WheelSlots.SLOT_PURPLE_TOP_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",

    },
    [WheelSlots.SLOT_BLUE_MIDDLE_100] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 5,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_BLUE_BOTTOM_150, WheelSlots.SLOT_BLUE_TOP_150 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_BLUE_BOTTOM_100] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 6,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_BLUE_TOP_150, WheelSlots.SLOT_PURPLE_BOTTOM_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_BLUE_TOP_75] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 2,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_BLUE_MIDDLE_100, WheelSlots.SLOT_BLUE_TOP_100, WheelSlots.SLOT_PURPLE_TOP_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_BLUE_BOTTOM_75] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 3,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_BLUE_MIDDLE_100, WheelSlots.SLOT_BLUE_BOTTOM_100, WheelSlots.SLOT_PURPLE_BOTTOM_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_BLUE_50] = {
        quadrant = "bottom_left",
        border = "bottom_left",
        color = "BottomLeft",
        index = 1,
        currentPoints = 0,
        totalPoints = 50,
        adjacents = { WheelSlots.SLOT_BLUE_BOTTOM_75, WheelSlots.SLOT_BLUE_TOP_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_PURPLE_200] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 9,
        currentPoints = 0,
        totalPoints = 200,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = {}
    },
    [WheelSlots.SLOT_PURPLE_TOP_150] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 7,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_PURPLE_200, WheelSlots.SLOT_PURPLE_BOTTOM_150 }
    },
    [WheelSlots.SLOT_PURPLE_BOTTOM_150] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 8,
        currentPoints = 0,
        totalPoints = 150,
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
        adjacents = { WheelSlots.SLOT_PURPLE_200, WheelSlots.SLOT_PURPLE_TOP_150 }
    },
    [WheelSlots.SLOT_PURPLE_TOP_100] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 4,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_PURPLE_TOP_150, WheelSlots.SLOT_BLUE_TOP_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_PURPLE_MIDDLE_100] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 5,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_PURPLE_TOP_150, WheelSlots.SLOT_PURPLE_BOTTOM_150 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_PURPLE_BOTTOM_100] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 6,
        currentPoints = 0,
        totalPoints = 100,
        adjacents = { WheelSlots.SLOT_PURPLE_BOTTOM_150, WheelSlots.SLOT_RED_BOTTOM_100 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_PURPLE_TOP_75] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 2,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_PURPLE_MIDDLE_100, WheelSlots.SLOT_PURPLE_TOP_100, WheelSlots.SLOT_BLUE_TOP_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_PURPLE_BOTTOM_75] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 3,
        currentPoints = 0,
        totalPoints = 75,
        adjacents = { WheelSlots.SLOT_PURPLE_MIDDLE_100, WheelSlots.SLOT_PURPLE_BOTTOM_100, WheelSlots.SLOT_RED_BOTTOM_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
    [WheelSlots.SLOT_PURPLE_50] = {
        quadrant = "bottom_right",
        border = "bottom_right",
        color = "BottomRight",
        index = 1,
        currentPoints = 0,
        totalPoints = 50,
        adjacents = { WheelSlots.SLOT_PURPLE_BOTTOM_75, WheelSlots.SLOT_PURPLE_TOP_75 },
        isHovered = false,
        isComplete = false,
        isSelected = false,
        isAdjacent = false,
        colorPath = "",
        hoverPath = "",
        adjacentPath = "",
        borderPath = "",
    },
}

local function propagateAdjacentSelection(slotList, controller)
    local byQuadrant = {}
    for index, data in ipairs(slotList) do
        local slotData = controller.wheel.data[index]
        if slotData then
            slotData.adjacentPath = ""
            if data.isComplete then
                local colorPath = controller.wheel.getSlotFramePercentage(data)
                slotData.colorPath = colorPath
                slotData.isAdjacent = true
                for _, slotId in ipairs(controller.wheel.slots[data.id].adjacents) do
                    table.insert(byQuadrant, slotId)
                end
            else
                if data.currentPoints > 0 then
                    local colorPath = controller.wheel.getSlotFramePercentage(data)
                    slotData.colorPath = colorPath
                    slotData.isAdjacent = true
                else
                    slotData.colorPath = ""
                    slotData.isAdjacent = false
                end
            end
        end
    end

    for _, slotId in ipairs(byQuadrant) do
        for index, data in ipairs(controller.wheel.data) do
            if data.id == slotId then
                controller.wheel.data[index].isAdjacent = true
                if data.currentPoints == 0 then
                    controller.wheel.data[index].adjacentPath = controller.wheel.data[index].adjacentPath
                elseif data.currentPoints < data.totalPoints then
                    controller.wheel.data[index].adjacentPath = controller.wheel.getSlotFramePercentage(data)
                end
                break
            end
        end
    end
end


local wod = {
    WheelSlots = WheelSlots,
    WheelSlotsParser = WheelSlotsParser,
    propagateAdjacentSelection = propagateAdjacentSelection,

}
return wod
