---
name: Analysis - Review Dog

on:
  pull_request:

jobs:

  cppcheck:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@main

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.3

      - name: Setup cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: cppcheck
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd "$GITHUB_WORKSPACE"
          cppcheck --version
          reviewdog -reporter=github-pr-check -runners=cppcheck


  luac:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@main

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.3

      - name: Setup Lua/Luacheck
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev lua-check

      - name: luac
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd "$GITHUB_WORKSPACE"
          luac -v
          reviewdog -reporter=github-pr-check -runners=luac


  luacheck:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@main

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.3

      - name: Setup Lua/Luacheck
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev lua-check

      - name: luacheck
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          luacheck --version
          cd "$GITHUB_WORKSPACE"
          reviewdog -reporter=github-pr-check -runners=luacheck


  shellcheck:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@main

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.15.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          pattern: '*.sh'
          exclude: './.git/*'


  xmllint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@main

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.3

      - name: Setup xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: xmllint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd "$GITHUB_WORKSPACE"
          xmllint --version
          reviewdog -reporter=github-pr-check -runners=xmllint


  yamllint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@main

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check


  hadolint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@main

      - name: hadolint
        uses: reviewdog/action-hadolint@v1.33.0
        with:
          reporter: github-pr-check

  actionlint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@main

      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
