name: Tests - Lua

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
    - "mods/**"
    - "modules/**"
  merge_group:
  push:
    paths:
    - "mods/**"
    - "modules/**"
    branches:
    - main

jobs:
  job:
    name: Run Lua Tests
    runs-on: ubuntu-latest

    steps:
    - name: Update
      run: sudo apt-get update

    - name: Setup Lua
      run: sudo apt-get install -y lua5.1 liblua5.1-0-dev

    - name: Check out code.
      uses: actions/checkout@main
